version: "3.9"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=kuro-photos
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  app:
    image: kurovale/kuro-photos
    environment:
      - DB_DATABASE=kuro-photos
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=pass
      - DB_USERNAME=root
    ports:
      - 8000:8000
    depends_on:
        db:
          condition: service_healthy
